package ca.intfast.iftimer.util

import android.content.ContentValues
import android.database.Cursor
import ca.intfast.iftimer.db.DbColumn

// --------------------------------------------------------------------------------------------------------------------------
// Must be implemented by all model classes, representing different entities of the application (like Emp, Dept etc.).
// That will allow CrudHelper class to manipulate with those classes in its CRUD functions.
// This interface forces you to write pure technical boilerplate code (population of ContentValues and reading from Cursor)
// separately from the business logic, which makes that logic easier to write and, later, understand.
// https://tinyurl.com/SQLiteCRUD
// --------------------------------------------------------------------------------------------------------------------------

interface Crudable {
    /***********************************************************************************************************************/
    val TABLE_NAME: String
    /***********************************************************************************************************************/
    val ID_COL_NAME: String
        get() = DbColumn.ID // override if the ID column name is not "_id"
    /***********************************************************************************************************************/
    var id: Int?
    // Override this way:
    // override var id: Int? = null
    /***********************************************************************************************************************/
    fun extractContentValues(): ContentValues
    // Called from insert() and update() of CrudHelper.

    // Just copy-paste to the descendant and customize according to the fields in that descendant:
    //    override fun extractContentValues() : ContentValues {
    //        val cv = ContentValues()
    //        // DON'T PUT PK FIELD(S) - PK IS AUTOGENERATED (ON INSERT) OR SUPPLIED WITHIN WHERE CLAUSE (ON UPDATE)
    //        cv.put(DbColumn.FIRST_NAME, this.firstName)
    //        cv.put(DbColumn.LAST_NAME, this.lastName)
    //        cv.put(DbColumn.DOB, this.dob)
    //        cv.put(DbColumn.IS_ACTIVE, this.isActive)
    //        return cv
    //    }
    /***********************************************************************************************************************/
    fun populateFromCursor(cursor: Cursor)
    // Called from retrieveListBySql() of CrudHelper.

    // Just copy-paste to the descendant and customize according to the fields in that descendant:
    //    override fun populateFromCursor(cursor: Cursor) {
    //        this.id = cursor.getInt(DbColumn.ID) // https://tinyurl.com/CursorInterface
    //        this.firstName = cursor.getString(DbColumn.FIRST_NAME)
    //        this.lastName = cursor.getString(DbColumn.LAST_NAME)
    //        this.dob = cursor.getLocalDate(DbColumn.DOB)
    //        this.isActive = cursor.getBoolean(DbColumn.IS_ACTIVE)
    //    }
    /***********************************************************************************************************************/
} // interface Crudable